"""first migration

Revision ID: 71cf3dafb5d5
Revises: 
Create Date: 2026-08-29 21:46:26.497120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71cf3dafb5d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('smtp_server', sa.String(length=150), nullable=False),
    sa.Column('smtp_account', sa.String(length=150), nullable=False),
    sa.Column('smtp_password', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('smtp_account_idx', 'accounts', ['smtp_account'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('smtp_account_idx', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
